# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
spec:
  replicas: 2 # adjust the number of replicas as needed
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - name: tetris
          image: timour259/tetrisv2 # Replace with the actual image tag
          ports:
            - containerPort: 80 # containerport
